### PR TITLE
Display Bob key size in help and version commands output

### LINKED ISSUE #325: Display Bob key size in `help` and `version` commands output

### LINKED ISSUE #328: Update `--version` output format
Currently `--version` prints: 
```
bob-apps 2.0.0-alpha.3-152d3fe1, built on 09-09-2021(12:41:49), (pearl 0.6.1-hash-undefined, built on 09-09-2021(12:40:39))
```

It has poor readability and incorrect pearl commit hash and pearl build time.
I suggest the following format:
```
bob 2.0.0-alpha.3 (key size: 8, commit: 152d3fe1, built on: 09-09-2021 12:41:49)
pearl 0.6.1       (commit: ...., built on: ....)
```

If it is not possible to fix printing pearl commit hash and build time, then it is better not to print them at all

### PR DESCRIPTION
**Pull request by pyakushin**
Closes #325 
Closes #328

### CODE REVIEW

**Comment by pyakushin** [comment]
# `./bobd --version`
```
bobd 2.0.0-alpha.3
bob 2.0.0-alpha.3 (key size: 8, commit: hash-undefined, built on: 14-09-2021(18:25:28))
pearl 0.6.2 (commit: hash-undefined, built on: 14-09-2021(18:25:18))
```
# `./bobd --help`
```
bobd 2.0.0-alpha.3
bob 2.0.0-alpha.3 (key size: 8, commit: hash-undefined, built on: 14-09-2021(18:27:07))
pearl 0.6.2 (commit: hash-undefined, built on: 14-09-2021(18:25:18))


USAGE:
    bobd [OPTIONS]

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information

OPTIONS:
    -c, --cluster <cluster>       cluster config file
    -p, --port <http_api_port>    http api port [default: 8000]
    -a, --name <name>             node name
    -n, --node <node>             node config file
    -t, --threads <threads>       count threads [default: 4]
```

File: bob/src/build_info/mod.rs [hunk 1]
```diff
@@ -0,0 +1,70 @@
...
+    pearl: PearlBuildInfo,
+}
+
+impl BuildInfo {
+    pub fn new() -> Self {
+        Self {
+            name: env!("CARGO_PKG_NAME"),
+            version: env!("CARGO_PKG_VERSION"),
+            key_size: BOB_KEY_SIZE,
+            commit: option_env!("PEARL_COMMIT_HASH").unwrap_or("hash-undefined"),
```
Comment (ikopylov) [inline bob/src/build_info/mod.rs:25]: `BOB_COMMIT_HASH` should be here

File: bob/src/build_info/build_time.rs [hunk 2]
```diff
@@ -0,0 +1 @@
+pub const BUILD_TIME: &str = "time-undefined";
```
Comment (ikopylov) [inline bob/src/build_info/build_time.rs:1]: This file is generated at build time. Perhaps it can be removed from the repo and added to `.gitignore` to prevent committing automatic changes to it
