### PR TITLE
Fix connectivity issues in Docker Swarm

### LINKED ISSUE #249: Investigate and fix connectivity issues when Bob is running inside Docker Swarm
In Docker Swarm environment, Bob addresses are configured with hostnames (not with ip-addresses)

### PR DESCRIPTION
**Pull request by vovac12**
Closes #249

### CODE REVIEW

File: bob-apps/bin/bobd.rs [hunk 1]
```diff
@@ -34,7 +34,16 @@ async fn main() {
     log4rs::init_file(node.log_config(), Default::default()).expect("can't find log config");
 
     let mut mapper = VirtualMapper::new(&node, &cluster).await;
-    let mut addr = node.bind().to_socket_addrs().unwrap().next().unwrap();
+
+    let mut addr = if let Some(addr) = node.bind_to_ip_address() {
+        addr
```
Comment (ikopylov) [inline bob-apps/bin/bobd.rs:39]: Sanity check is required: if `bind_to_ip_address` is specified and `node` address is also specified as ipv4 and they are different, then log error and panic

File: bob-apps/bin/bobd.rs [hunk 2]
```diff
@@ -34,7 +34,16 @@ async fn main() {
...
+    } else if let Ok(addr) = node.bind().parse() {
```
Comment (ikopylov) [inline bob-apps/bin/bobd.rs:40]: Into what type is this string parsed?

**Comment by ikopylov** [comment]
@pyakushin this change is needed ASAP. Please, review it.

File: bob-apps/bin/bobd.rs (hunk 2 above)
Comment (vovac12) [reply bob-apps/bin/bobd.rs:40]: `std::net::SocketAddr`

File: bob-apps/bin/bobd.rs (hunk 1 above)
Comment (vovac12) [reply bob-apps/bin/bobd.rs]: Done

File: bob-apps/bin/bobd.rs [hunk 3]
```diff
@@ -44,8 +63,15 @@ async fn main() {
             .find(|n| n.name() == name)
             .unwrap_or_else(|| panic!("cannot find node: '{}' in cluster config", name));
         mapper = VirtualMapper::new(&node, &cluster).await;
-        addr = finded.address().to_socket_addrs().unwrap().next().unwrap();
+        addr = if let Ok(addr) = finded.address().parse() {
```
Comment (idruzhitskiy) [inline bob-apps/bin/bobd.rs:66]: Typo: finded -> found

File: bob-apps/bin/bobd.rs [hunk 4]
```diff
@@ -34,7 +34,26 @@ async fn main() {
...
+            if addr1 == addr2 {
+                Some(addr1)
+            } else {
+                log::error!("Addresses provided in node config and cluster config are not equal: {:?} != {:?}", addr1, addr2);
+                None
+            }
+        }
+        (Some(addr), _, _) => Some(addr),
+        (_, Ok(addr), _) => Some(addr),
+        (_, _, Some(port)) => Some(SocketAddr::new(IpAddr::V4(Ipv4Addr::new(0, 0, 0, 0)), port)),
```
Comment (idruzhitskiy) [inline bob-apps/bin/bobd.rs:53]: `SocketAddr::new(IpAddr::V4(Ipv4Addr::new(0, 0, 0, 0)), port)` occured multiple times in the code, prob it's better to add some function for it (since it's quite a long line)

Comment (pyakushin) [reply bob-apps/bin/bobd.rs:53]: Or `type`

File: bob-common/src/node.rs [hunk 5]
```diff
@@ -39,8 +38,7 @@ pub struct Disk {
 impl Node {
     pub async fn new(name: String, address: &str, index: u16) -> Self {
         error!("address: [{}]", address);
```
Comment (pyakushin) [inline bob-common/src/node.rs:40]: debug code

File: bob-common/src/node.rs [hunk 6]
```diff
@@ -39,8 +38,7 @@ pub struct Disk {
...
-        let mut address = lookup_host(address).await.expect("DNS resolution failed");
-        let address = address.next().expect("address is empty");
+        let address = address.to_string();
```
Comment (pyakushin) [inline bob-common/src/node.rs:41]: Pass address as `String` already because you make it owned here anyway

File: bob-apps/bin/bobd.rs (hunk 3 above)
Comment (vovac12) [reply bob-apps/bin/bobd.rs]: Fixed

File: bob-apps/bin/bobd.rs (hunk 4 above)
Comment (vovac12) [reply bob-apps/bin/bobd.rs]: Function created

File: bob-common/src/node.rs (hunk 5 above)
Comment (vovac12) [reply bob-common/src/node.rs]: Fixed

File: bob-common/src/node.rs (hunk 6 above)
Comment (vovac12) [reply bob-common/src/node.rs]: Fixed
