### PR TITLE
530 internode auth fix

### LINKED ISSUE #530: Authorization: inter-node authentication does not work for some nodes in cluster

### PR DESCRIPTION
**Pull request by Boneyan**
Fixed internode authorization error
Closes #530

### CODE REVIEW

File: bob-common/src/node.rs [hunk 1]
```diff
@@ -82,12 +82,12 @@ impl Node {
         self.conn.read().await.clone()
     }
 
-    pub async fn check(&self, client_fatory: &Factory) -> Result<(), String> {
+    pub async fn check(&self, client_factory: &Factory, local_node_name: &String) -> Result<(), String> {
```
Comment (ikopylov) [inline bob-common/src/node.rs:85]: This change seems to break the idea of factory pattern. `local_node_name` should be part of `Factory`, not the separate argument

**Comment by ikopylov** [comment]
@Boneyan Please, check whether these changes fixed the same bug in Docker Swarm (https://github.com/qoollo/bob/issues/529)

**Review by ikopylov — APPROVED** [review]
LGTM 
Need a test inside Swarm
