### PR TITLE
Fix of "Config validation bug that misses the case where the quorum value exceeds the number of replicas"

### LINKED ISSUE #130: Config validation bug that misses the case where the quorum value exceeds the number of replicas

### PR DESCRIPTION
**Pull request by Justarone**
closes #130

### CODE REVIEW

File: src/core/configs/cluster.rs [hunk 1]
```diff
@@ -287,6 +287,9 @@ impl Cluster {
                 debug!("cannot find node: {} in cluster config", node.name());
                 format!("cannot find node: {} in cluster config", node.name())
             })?;
+        if self.vdisks().iter().any(|vdisk| vdisk.replicas().len() < node.quorum()) {
+            return Err(String::from("Quorum is more than amount of replicas for at least one VDisk"));
```
Comment (ikopylov) [inline src/core/configs/cluster.rs:291]: `vdisk` name should be specified inside the error description. This will make it easier to find and fix the problem

Comment (Justarone) [reply src/core/configs/cluster.rs]: Done in new commit!

**Comment by ikopylov** [comment]
LGTM
