### PR TITLE
528 correct auth error bobp

### LINKED ISSUE #528: Authorization: print correct error message when authentication failed in `bobp`
Currently, if `user` and `password` are not supplied, it prints ` InvalidArgument` error. In this case `bobp` should print error, related to authentication

### PR DESCRIPTION
**Pull request by Boneyan**
"CredentialsNotProvided" now has "Unauthenticated" code
Closes #528

### CODE REVIEW

File: bob-access/src/error.rs [hunk 1]
```diff
@@ -63,7 +63,7 @@ impl Error {
             Os(_) => Code::Internal,
             UserNotFound => Code::PermissionDenied,
             ConversionError(_) => Code::InvalidArgument,
-            CredentialsNotProvided(_) => Code::InvalidArgument,
+            CredentialsNotProvided(_) => Code::Unauthenticated,
```
Comment (ikopylov) [inline bob-access/src/error.rs:66]: Please, update other codes too:
`UserNotFound => Code::Unauthenticated`
`UnauthorizedRequest => Code::Unauthenticated`

File: CHANGELOG.md [hunk 2]
```diff
@@ -4,7 +4,7 @@ Bob versions changelog
 
 ## [Unreleased]
 #### Added
-
+- "CredentialsNotProvided", "UserNotFound", "UnauthorizedRequest" now have "Unauthenticated" code (#528)
```
Comment (ikopylov) [inline CHANGELOG.md:7]: This line is more relevant to `Fixed` section

**Review by ikopylov — APPROVED** [review]
LGTM
