### PR TITLE
447 migration not updating version header

### LINKED ISSUE #447: `brt`: BLOB migration does not update version number in header

### LINKED ISSUE #448: `brt`: incorrect default target version for BLOB migration command
In the help the default target version is `2`, which is incorrect. The correct value is `1`

### PR DESCRIPTION
**Pull request by Boneyan**
Version in BlobHeader now changes during migration
Closes #447
Closes #448

### CODE REVIEW

File: bob-apps/bin/blob_recovery_tool/structs.rs [hunk 1]
```diff
@@ -81,6 +81,13 @@ impl Validatable for BlobHeader {
     }
 }
 
+impl BlobHeader {
+    pub(crate) fn migrate(mut self, target: u32) -> AnyResult<Self> {
```
Comment (idruzhitskiy) [inline bob-apps/bin/blob_recovery_tool/structs.rs:85]: Why not `version` as argument?

File: bob-apps/bin/blob_recovery_tool/structs.rs [hunk 2]
```diff
@@ -81,6 +81,13 @@ impl Validatable for BlobHeader {
     }
 }
 
+impl BlobHeader {
+    pub(crate) fn migrate(mut self, version: u32) -> AnyResult<Self> {
```
Comment (ikopylov) [inline bob-apps/bin/blob_recovery_tool/structs.rs:85]: The signature should be the same as in `Record.migrate`. It should receive source_version and target_version as parameters. Also the behavior should be the same: you need to explicitly restrict possible migrations

**Comment by ikopylov** [comment]
LGTM
