### PR TITLE
830 lsof zombie fix

### LINKED ISSUE #830: Bob produces `lsof` zombie child processes
`lsof` is used in hardware metrics to calculate the number of opened file descriptors (https://github.com/qoollo/bob/blob/master/bob/src/hw_metrics_collector.rs#L492). For unknown reasons, these processes sometimes become zombies. The problem was noticed when working in docker

### PR DESCRIPTION
**Pull request by idruzhitskiy**
Closes #830

### CODE REVIEW

File: bob/src/hw_metrics_collector.rs [hunk 1]
```diff
@@ -473,50 +474,63 @@ impl DescrCounter {
...
+                                                return Some(count - 5); // exclude stdin, stdout, stderr, lsof pipe and wc pipe
+                                            }
+                                            Err(e) => {
+                                                debug!("failed to parse lsof result: {}", e);
+                                            }
+                                        }
+                                    },
                                     Err(e) => {
-                                        debug!("failed to parse lsof result: {}", e);
+                                        debug!("can't use lsof, wc error (fs /proc will be used): {}", e);
```
Comment (ikopylov) [inline bob/src/hw_metrics_collector.rs:518]: Why are the error messages swapped?

**Comment by ikopylov** [comment]
Have you checked that descriptors counting works properly after these changes?

File: bob/src/hw_metrics_collector.rs (hunk 1 above)
Comment (idruzhitskiy) [reply bob/src/hw_metrics_collector.rs:518]: There is another level of match added

Comment (ikopylov) [reply bob/src/hw_metrics_collector.rs:518]: Good. Git diff a little bit misleading here. In the whole file I see, that everything is correct.

The level of nesting became very large, but I did not find an easy way to refactor it, since we process each error independently

**Review by ikopylov — APPROVED** [review]
LGTM
