### PR TITLE
420 error logging reduce

### LINKED ISSUE #420: Reduce logging intensity during disk disconnection
Currently, for every PUT request for that disk the following log with ERROR level is written:
`2022-01-28 19:20:56 bob_backend::core:245 ERROR PUT[D7A6440000000000][disk8] local failed: Error { ctx: Failed("Error {\n ctx: DCIsNotAvailable,\n}") }`

This message should be written on DEBUG level.
And at the ERROR level, the message should accumulate the number of errors for each disk and write it every 5 seconds. Something like:
`2022-01-28 19:20:56 bob_backend::core:245 ERROR PUT failed 100500 times on disk8.  Error { ctx: Failed("Error {\n ctx: DCIsNotAvailable,\n}") }`

### PR DESCRIPTION
**Pull request by Boneyan**
Same put error logs now agregate in one line every error_log_interval (in case of disk disconnection)
Closes #420

### CODE REVIEW

File: bob-common/src/configs/node.rs [hunk 1]
```diff
@@ -481,6 +481,8 @@ pub struct Node {
     #[serde(skip)]
     disks_ref: Arc<Mutex<Vec<DiskPath>>>,
 
+    #[serde(default = "Node::default_error_log_interval")]
+    error_log_interval: String,
```
Comment (ikopylov) [inline bob-common/src/configs/node.rs:485]: This parameter is redundant. It value will never change. It is better to remove the part related to the config and just declare a constant at the place of use

File: bob-backend/src/core.rs [hunk 2]
```diff
@@ -149,7 +216,12 @@ impl Backend {
                 Arc::new(pearl)
             }
         };
-        Self { inner, mapper }
+
+        let error_logger = 
+            Arc::new(Mutex::new(BackendErrorLogger::new(config.error_log_interval())));
+        BackendErrorLogger::spawn_task(error_logger.clone());
```
Comment (ikopylov) [inline bob-backend/src/core.rs:222]: Too much complexity for simple logging. This task can be done without additional thread by measuring time intervals. Example on C#: https://github.com/qoollo/dotNet-turbo/blob/master/src/Qoollo.Turbo/Common/EventTimingTracker.cs

File: bob-backend/src/core.rs [hunk 3]
```diff
@@ -131,10 +134,74 @@ pub trait MetricsProducer: Send + Sync {
...
+            errors: HashMap::new(),
+            interval,
+        }
+    }
+
+    fn report_error(&mut self, action: BackendErrorAction) {
+        if let Some(count) = self.errors.get_mut(&action) {
+            *count += 1;
+        } else {
+            self.errors.insert(action, 1);
```
Comment (ikopylov) [inline bob-backend/src/core.rs:160]: This is not thread safe. `task` function can access `errors` while this `insert` in progress

File: bob-backend/src/core.rs (hunk 2 above)
Comment (ikopylov) [reply bob-backend/src/core.rs:222]: For fast time measurement use this crate: https://docs.rs/coarsetime/latest/coarsetime/

File: bob-backend/src/core.rs [hunk 4]
```diff
@@ -1,4 +1,7 @@
 use crate::prelude::*;
+use std::collections::HashMap;
+use std::sync::Mutex;
+use coarsetime::{Duration as CDuration,Instant};
```
Comment (ikopylov) [inline bob-backend/src/core.rs:4]: Please, import `Instant` also with `C` prefix to see places where `coarsetime` is used

File: bob-backend/src/core.rs [hunk 5]
```diff
@@ -131,10 +134,66 @@ pub trait MetricsProducer: Send + Sync {
...
 
+const ERROR_LOG_INTERVAL: u64 = 5000;
+
+#[derive(Hash, PartialEq, Eq, Debug)]
+enum BackendErrorAction {
+    PUT(String, String),
+}
+
+#[derive(Debug)]
+struct BackendErrorLogger {
```
Comment (ikopylov) [inline bob-backend/src/core.rs:145]: I suggest to make this type a little bit more universal. Error type can be a generic parameter, allowing the type to be used in other places. Also it would nice to rename the struct to something more universal (e.g. `IntervalErrorLogger`). Additionally, this struct can be moved to a separate file

File: bob-backend/src/core.rs [hunk 6]
```diff
@@ -131,10 +134,66 @@ pub trait MetricsProducer: Send + Sync {
...
+    errors: HashMap<BackendErrorAction, u64>,
+    interval: CDuration,
+    last_timestamp: CInstant,
+}
+
+impl BackendErrorLogger {
+    fn new() -> BackendErrorLogger {
```
Comment (ikopylov) [inline bob-backend/src/core.rs:152]: `interval` should be passed as parameter

File: bob-backend/src/core.rs [hunk 7]
```diff
@@ -131,10 +134,66 @@ pub trait MetricsProducer: Send + Sync {
...
+        BackendErrorLogger {
+            errors: HashMap::new(),
+            interval: CDuration::from_millis(ERROR_LOG_INTERVAL),
+            last_timestamp: CInstant::now(),
+        }
+    }
+
+    fn report_error(logger: Arc<Mutex<BackendErrorLogger>>, action: BackendErrorAction) {
```
Comment (ikopylov) [inline bob-backend/src/core.rs:160]: All methods in this type should work directly with inner fields. `Arc` and `Mutex` are the things, that are created in the place of use when needed

Comment (ikopylov) [reply bob-backend/src/core.rs:160]: Or you can take another approach: declare inner struct with HashMap and Timestamp and protect it with Mutex inside this struct

Comment (ikopylov) [reply bob-backend/src/core.rs:160]: One problem: Mutex potentially can be under a high contention. Try to use Mutex from https://crates.io/crates/parking_lot crate. It implements spinning strategy, that should highly improve performance in our scenario

File: bob-backend/src/interval_logger.rs [hunk 8]
```diff
@@ -0,0 +1,42 @@
+use coarsetime::{Duration as CDuration, Instant as CInstant};
+use std::{
+    collections::HashMap,
+    hash::Hash,
+    cmp::Eq,
+    fmt::Display
+};
+
+#[derive(Debug)]
+pub struct IntervalErrorLogger<E> {
```
Comment (ikopylov) [inline bob-backend/src/interval_logger.rs:10]: Add an additional struct `IntervalErrorLoggerSafe<E>` that wraps `IntervalErrorLogger<E>` protected by Mutex. This structure will hide the synchronization behind the scenes and thus simplify the caller's code.

File: bob-backend/src/interval_logger.rs [hunk 9]
```diff
@@ -0,0 +1,60 @@
...
+    interval: CDuration,
+    last_timestamp: CInstant,
+}
+
+impl<E: Hash + Eq + Display> IntervalErrorLogger<E> {
+    pub fn new(interval_ms: u64) -> Self {
+        Self {
+            errors: HashMap::new(),
+            interval: CDuration::from_millis(interval_ms),
+            last_timestamp: CInstant::now(),
```
Comment (ikopylov) [inline bob-backend/src/interval_logger.rs:22]: I suggest subtracting the `interval` to ensure that the very first message is always logged

File: bob-backend/src/interval_logger.rs [hunk 10]
```diff
@@ -0,0 +1,61 @@
...
+    last_timestamp: CInstant,
+}
+
+impl<E: Hash + Eq + Display> IntervalErrorLogger<E> {
+    pub fn new(interval_ms: u64) -> Self {
+        let interval = CDuration::from_millis(interval_ms);
+        Self {
+            errors: HashMap::new(),
+            interval,
+            last_timestamp: CInstant::now() - interval,
```
Comment (ikopylov) [inline bob-backend/src/interval_logger.rs:23]: I was thinking that it would be nice to additionally subtract 1ms

**Review by ikopylov — APPROVED** [review]
LGTM
