### PR TITLE
779 fix warning

### LINKED ISSUE #779: `rustc-serialize` package generates warning
```
warning: the following packages contain code that will be rejected by a future version of Rust: rustc-serialize v0.3.24
Warning: note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 1`
```

### PR DESCRIPTION
**Pull request by idruzhitskiy**
Closes #779

### CODE REVIEW

File: bob-common/src/stopwatch.rs [hunk 1]
```diff
@@ -0,0 +1,121 @@
...
+    /// Returns the elapsed time since the start of the stopwatch in milliseconds.
+    pub fn elapsed_ms(&self) -> i64 {
+        let dur = self.elapsed();
+        return (dur.as_secs() * 1000 + (dur.subsec_nanos() / 1000000) as u64) as i64;
+    }
+
+    /// Returns the elapsed time since last split or start/restart.
+    ///
+    /// If the stopwatch is in stopped state this will always return a zero Duration.
+    pub fn elapsed_split(&mut self) -> Duration {
```
Comment (ikopylov) [inline bob-common/src/stopwatch.rs:98]: I didn't found the places where `elapsed_split` or `elapsed_split_ms` are used, so I suggest to remove these functions

File: bob-common/src/stopwatch.rs [hunk 2]
```diff
@@ -0,0 +1,121 @@
+use std::default::Default;
+use std::fmt;
+use std::time::{Duration, Instant};
+
+#[derive(Clone, Copy)]
+pub struct Stopwatch {
```
Comment (ikopylov) [inline bob-common/src/stopwatch.rs:6]: When you'll remove `elapsed_split`, this `struct` can be transformed into 3-state `enum`:
```
pub enum Stopwatch {
    NotStarted,
    Started(Instant),
    Stopped(Duration)
}
```

File: bob-common/src/stopwatch.rs [hunk 3]
```diff
@@ -0,0 +1,121 @@
...
+            }
+            // stopwatch is not running
+            None => {
+                return self.elapsed;
+            }
+        }
+    }
+
+    /// Returns the elapsed time since the start of the stopwatch in milliseconds.
+    pub fn elapsed_ms(&self) -> i64 {
```
Comment (ikopylov) [inline bob-common/src/stopwatch.rs:90]: Hm, that is strange, that it returns `i64`. The result should be obviously unsigned: `u64`

File: bob-common/src/stopwatch.rs [hunk 4]
```diff
@@ -0,0 +1,121 @@
...
+        let dur = self.elapsed();
+        return (dur.as_secs() * 1000 + (dur.subsec_nanos() / 1000000) as u64) as i64;
```
Comment (ikopylov) [inline bob-common/src/stopwatch.rs:92]: I think it is better to use `dur.as_millis()` here

**Comment by ikopylov** [comment]
Add a line to `CHANGELOG.md`

**Comment by ikopylov** [comment]
Also, please port 2 changes from this request (where the `sw.elapsed_ms()` call has moved to the `debug!` macro parameter, these places are marked with my comments there): https://github.com/qoollo/bob/pull/613/files
I want to close #613, but these 2 changes are better to keep

File: CHANGELOG.md [hunk 5]
```diff
@@ -21,6 +21,7 @@ Bob versions changelog
 #### Fixed
 - Fix incorrect exist result due to variables sharing between keys (#762)
 - Fix unit of measurement of memory in hardware metrics (#772)
+- Fix rust depreceation warning (#779)
```
Comment (ikopylov) [inline CHANGELOG.md:24]:
```suggestion
- Fix rust deprecation warning (#779)
```

File: bob-common/src/stopwatch.rs [hunk 6]
```diff
@@ -0,0 +1,85 @@
...
+    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
+        return write!(f, "{}ms", self.elapsed_ms());
+    }
+}
+
+impl Stopwatch {
+    /// Returns a new stopwatch.
+    pub fn new() -> Stopwatch {
+        let sw: Stopwatch = Default::default();
+        return sw;
```
Comment (ikopylov) [inline bob-common/src/stopwatch.rs:35]: Just `Self::default()`

File: bob-common/src/stopwatch.rs [hunk 7]
```diff
@@ -0,0 +1,85 @@
...
+            StopwatchState::NotStarted => Duration::ZERO,
+            StopwatchState::Started(i) => i.elapsed(),
+            StopwatchState::Stopped(d) => d,
+        }
+    }
+
+    /// Returns the elapsed time since the start of the stopwatch in milliseconds.
+    pub fn elapsed_ms(&self) -> u64 {
+        let dur = self.elapsed();
+        dur.as_millis() as u64 + (dur.subsec_nanos() / 1000000) as u64
```
Comment (ikopylov) [inline bob-common/src/stopwatch.rs:83]:
```suggestion
        dur.as_millis() as u64
```

**Review by ikopylov — APPROVED** [review]
LGTM
