### PR TITLE
Possible metrics gap fix

### LINKED ISSUE #274: Metrics transferred to graphite contain gaps
In graphite all metrics periodically have gaps. It was noted that these gaps often occur under load

### PR DESCRIPTION
**Pull request by Justarone**
Seems like this is the reason why metrics have "gaps" on graphite side, but maybe this reason is not the only one
Closes #274

### CODE REVIEW

File: bob-common/src/metrics/exporter/send.rs [hunk 1]
```diff
@@ -18,34 +18,58 @@ pub(super) async fn send_metrics(
...
             }
+            current_time = Instant::now();
         }
+        let mut res_string = String::new();
+        let ts = chrono::Local::now().timestamp();
+        flush_counters(&counters_map, &mut res_string, &prefix, ts).await;
+        flush_gauges(&gauges_map, &mut res_string, &prefix, ts).await;
+        flush_times(&mut times_map, &mut res_string, &prefix, ts).await;
+        if let Err(e) = socket_sender.send(res_string).await {
+            debug!("Can't send data to tcp sender task (reason: {})", e);
```
Comment (pyakushin) [inline bob-common/src/metrics/exporter/send.rs:47]: I think it should be `warn` level. Because if sending failed there something serious happened with receiver side

File: bob-common/src/metrics/exporter/send.rs [hunk 2]
```diff
@@ -1,13 +1,13 @@
...
-use tokio::time::{interval, timeout};
+use std::time::{Duration, Instant};
+use tokio::sync::mpsc::{channel, Receiver, Sender};
+use tokio::time::timeout;
 
 use super::retry_socket::RetrySocket;
 use super::{Metric, MetricInner, MetricKey, MetricValue, TimeStamp};
 
-const METRICS_RECV_TIMEOUT: Duration = Duration::from_millis(100);
+const TCP_CHANNEL_SIZE: usize = 1024;
```
Comment (pyakushin) [inline bob-common/src/metrics/exporter/send.rs:10]: I suggest to name it differently, like `TCP_SENDER_QUEUE_SIZE` or `TCP_SENDER_BUFFER_SIZE` or smth like that

File: bob-common/src/metrics/exporter/send.rs [hunk 3]
```diff
@@ -18,34 +18,58 @@ pub(super) async fn send_metrics(
...
+    let (tx, rx) = channel(TCP_CHANNEL_SIZE);
+    let socket = RetrySocket::new(address.parse().expect("Can't read address from String")).await;
+    tokio::spawn(tcp_sender_task(socket, rx));
+    tx
+}
+
+async fn tcp_sender_task(mut socket: RetrySocket, mut rx: Receiver<String>) {
+    while let Some(data) = rx.recv().await {
+        if let Err(e) = socket.write_all(data.as_bytes()).await {
+            debug!(
```
Comment (pyakushin) [inline bob-common/src/metrics/exporter/send.rs:62]: Maybe also `warn`. It's not critical system, but it would be helpful to now if metrics export fails
